// Auto-generated by `amplify push` — replace placeholders after running the CLI setup.
// Do NOT put secrets here; Cognito pool IDs and API endpoints are public config.
const awsmobile = {
  aws_project_region: 'REGION',
  aws_cognito_region: 'REGION',
  aws_user_pools_id: 'REGION_XXXXXXXX',
  aws_user_pools_web_client_id: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
  aws_mandatory_sign_in: 'enable',
  aws_cloud_logic_custom: [
    {
      name: 'mmPlannerApi',
      endpoint: 'https://XXXXXXXXXX.execute-api.REGION.amazonaws.com/prod',
      region: 'REGION',
    },
  ],
};

export default awsmobile;
